import Head from "next/head";
import Footer from '../Shared/Footer';
import footerStyles from '../styles/Footer.module.scss';
import styles from '../styles/Home.module.scss';
import HomePage from '../view/pages/Home';
export default function Home() {
  return (
    <div>
      <Head>
        <title>TS4U #Best IT Training and Job</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage styles={styles}/>
      </main>

      <footer>
        <Footer styles={footerStyles}/>
      </footer>
    </div>
  );
}
